apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
        - name: event
          image: vl037/event
---
apiVersion: v1
kind: Service
metadata:
  name: event-srv
spec:
  # type: ClusterIP # could be excluded since it's the default 
  selector:
    app: event # matches template.metadata.lables
  ports:
    - name: event # only for logging purpose
      protocol: TCP
      port: 4005 # port for ClusterIP Service, could be random
      targetPort: 4005 # our container port

# kubectl apply -f [xxx].yaml
# kubectl rollout restart deployment [depl_name]
