apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: vl037/posts

# kubectl apply -f posts-depl.yaml
# kubectl rollout restart deployment [depl_name]
